### ISSUE TITLE
Chyby v číselníku "jiná časová specifikace"

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/lkod-mvcr#5]
https://github.com/opendata-mvcr/lkod-mvcr/blob/d80d63d1412139235fcfbfc5ff38352dabedfa55/%C4%8D%C3%ADseln%C3%ADky/jin%C3%A1-%C4%8Dasov%C3%A1-specifikace.jsonld#L2 (jíná)
https://github.com/opendata-mvcr/lkod-mvcr/blob/d80d63d1412139235fcfbfc5ff38352dabedfa55/%C4%8D%C3%ADseln%C3%ADky/jin%C3%A1-%C4%8Dasov%C3%A1-specifikace.jsonld#L92 (chybí ukončující závorka JSONLint!)

**Comment by jirkamarekbrno** [comment]
@jakubklimek hotovo. prosím o uzavření a PR
